// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct TournamentHubProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for TournamentHubProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = TournamentHubProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        TournamentHubProxyMethods { wrapped_tx: tx }
    }
}

pub struct TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> TournamentHubProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn fix_user_stats<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("fixUserStats")
            .argument(&user)
            .original_result()
    }

    pub fn fix_all_user_stats(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("fixAllUserStats")
            .original_result()
    }

    pub fn clear_all_data(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("clearAllData")
            .original_result()
    }

    pub fn register_game<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
        Arg1: ProxyArg<u32>,
        Arg2: ProxyArg<ManagedVec<Env::Api, u32>>,
        Arg3: ProxyArg<bool>,
    >(
        self,
        signing_server_address: Arg0,
        podium_size: Arg1,
        prize_distribution_percentages: Arg2,
        allow_late_join: Arg3,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerGame")
            .argument(&signing_server_address)
            .argument(&podium_size)
            .argument(&prize_distribution_percentages)
            .argument(&allow_late_join)
            .original_result()
    }

    pub fn set_house_fee_percentage<
        Arg0: ProxyArg<u32>,
    >(
        self,
        new_fee: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setHouseFeePercentage")
            .argument(&new_fee)
            .original_result()
    }

    pub fn submit_results<
        Arg0: ProxyArg<usize>,
        Arg1: ProxyArg<ManagedVec<Env::Api, ManagedAddress<Env::Api>>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        tournament_index: Arg0,
        winner_podium: Arg1,
        signed_result: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("submitResults")
            .argument(&tournament_index)
            .argument(&winner_podium)
            .argument(&signed_result)
            .original_result()
    }

    pub fn update_result_tx_hash<
        Arg0: ProxyArg<usize>,
        Arg1: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        tournament_index: Arg0,
        result_tx_hash: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("updateResultTxHash")
            .argument(&tournament_index)
            .argument(&result_tx_hash)
            .original_result()
    }

    pub fn place_spectator_bet<
        Arg0: ProxyArg<usize>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        tournament_index: Arg0,
        betting_on_player: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("placeSpectatorBet")
            .argument(&tournament_index)
            .argument(&betting_on_player)
            .original_result()
    }

    pub fn claim_spectator_winnings<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimSpectatorWinnings")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn create_tournament<
        Arg0: ProxyArg<u32>,
        Arg1: ProxyArg<u32>,
        Arg2: ProxyArg<u32>,
        Arg3: ProxyArg<BigUint<Env::Api>>,
        Arg4: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        game_index: Arg0,
        max_players: Arg1,
        min_players: Arg2,
        entry_fee: Arg3,
        name: Arg4,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("createTournament")
            .argument(&game_index)
            .argument(&max_players)
            .argument(&min_players)
            .argument(&entry_fee)
            .argument(&name)
            .original_result()
    }

    pub fn join_tournament<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("joinTournament")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn start_game<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("startGame")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn set_tournament_fee<
        Arg0: ProxyArg<BigUint<Env::Api>>,
    >(
        self,
        new_fee: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("setTournamentFee")
            .argument(&new_fee)
            .original_result()
    }

    pub fn get_prize_pool<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPrizePool")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn clear_all_tournaments(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("clearAllTournaments")
            .original_result()
    }

    pub fn get_game_config<
        Arg0: ProxyArg<usize>,
    >(
        self,
        game_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, GameConfig<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getGameConfig")
            .argument(&game_index)
            .original_result()
    }

    pub fn get_tournament<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, Tournament<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournament")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn get_number_of_tournaments(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, usize> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getNumberOfTournaments")
            .original_result()
    }

    pub fn get_number_of_games(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, usize> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getNumberOfGames")
            .original_result()
    }

    pub fn get_active_tournament_ids(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getActiveTournamentIds")
            .original_result()
    }

    pub fn get_tournament_basic_info<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, (u64, u64, u32, ManagedVec<Env::Api, ManagedAddress<Env::Api>>, ManagedAddress<Env::Api>, u32, u32, BigUint<Env::Api>, ManagedBuffer<Env::Api>, u64)> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournamentBasicInfo")
            .argument(&tournament_id)
            .original_result()
    }

    pub fn get_user_tournaments<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user_address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, (ManagedVec<Env::Api, u64>, ManagedVec<Env::Api, u64>)> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserTournaments")
            .argument(&user_address)
            .original_result()
    }

    pub fn get_spectator_bets<
        Arg0: ProxyArg<usize>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        tournament_index: Arg0,
        player: Arg1,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, SpectatorBet<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSpectatorBets")
            .argument(&tournament_index)
            .argument(&player)
            .original_result()
    }

    pub fn get_spectator_pool_total<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_index: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getSpectatorPoolTotal")
            .argument(&tournament_index)
            .original_result()
    }

    pub fn get_accumulated_house_fees(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAccumulatedHouseFees")
            .original_result()
    }

    pub fn get_tournament_fee(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournamentFee")
            .original_result()
    }

    pub fn get_house_fee_percentage(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u32> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getHouseFeePercentage")
            .original_result()
    }

    pub fn get_user_stats<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, UserStats<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserStats")
            .argument(&user)
            .original_result()
    }

    pub fn get_user_tournaments_created<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserTournamentsCreated")
            .argument(&user)
            .original_result()
    }

    pub fn get_user_tournaments_joined<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserTournamentsJoined")
            .argument(&user)
            .original_result()
    }

    pub fn get_user_tournaments_won<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, u64>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserTournamentsWon")
            .argument(&user)
            .original_result()
    }

    pub fn get_total_tournaments_created(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalTournamentsCreated")
            .original_result()
    }

    pub fn get_total_tournaments_completed(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u64> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalTournamentsCompleted")
            .original_result()
    }

    pub fn get_tournament_stats(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, (u64, u64, u64, u64, u64)> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournamentStats")
            .original_result()
    }

    pub fn get_max_prize_won(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getMaxPrizeWon")
            .original_result()
    }

    pub fn get_total_prize_distributed(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, BigUint<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTotalPrizeDistributed")
            .original_result()
    }

    pub fn get_prize_stats(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, (BigUint<Env::Api>, BigUint<Env::Api>)> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getPrizeStats")
            .original_result()
    }

    pub fn get_all_active_tournaments_basic_info(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, TournamentBasicInfo<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllActiveTournamentsBasicInfo")
            .original_result()
    }

    pub fn get_tournament_status_single<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, u32> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournamentStatusSingle")
            .argument(&tournament_id)
            .original_result()
    }

    pub fn get_tournament_basic_info_single<
        Arg0: ProxyArg<usize>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, TournamentBasicInfo<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getTournamentBasicInfoSingle")
            .argument(&tournament_id)
            .original_result()
    }

    pub fn get_user_stats_single<
        Arg0: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        user_address: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, UserStats<Env::Api>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getUserStatsSingle")
            .argument(&user_address)
            .original_result()
    }

    pub fn get_all_users_stats(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, UserStatsInfo<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllUsersStats")
            .original_result()
    }

    pub fn get_all_users_addresses(
        self,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ManagedVec<Env::Api, ManagedAddress<Env::Api>>> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("getAllUsersAddresses")
            .original_result()
    }
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct GameConfig<Api>
where
    Api: ManagedTypeApi,
{
    pub signing_server_address: ManagedAddress<Api>,
    pub podium_size: u32,
    pub prize_distribution_percentages: ManagedVec<Api, u32>,
    pub house_fee_percentage: u32,
    pub allow_late_join: bool,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct Tournament<Api>
where
    Api: ManagedTypeApi,
{
    pub game_id: u64,
    pub status: TournamentStatus,
    pub participants: ManagedVec<Api, ManagedAddress<Api>>,
    pub final_podium: ManagedVec<Api, ManagedAddress<Api>>,
    pub creator: ManagedAddress<Api>,
    pub max_players: u32,
    pub min_players: u32,
    pub entry_fee: BigUint<Api>,
    pub name: ManagedBuffer<Api>,
    pub created_at: u64,
    pub result_tx_hash: Option<ManagedBuffer<Api>>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub enum TournamentStatus {
    Joining,
    ReadyToStart,
    Active,
    ProcessingResults,
    Completed,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct SpectatorBet<Api>
where
    Api: ManagedTypeApi,
{
    pub bettor_address: ManagedAddress<Api>,
    pub amount: BigUint<Api>,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct UserStats<Api>
where
    Api: ManagedTypeApi,
{
    pub games_played: u32,
    pub wins: u32,
    pub losses: u32,
    pub win_rate: u32,
    pub tokens_won: BigUint<Api>,
    pub tokens_spent: BigUint<Api>,
    pub tournaments_created: u32,
    pub tournaments_won: u32,
    pub current_streak: u32,
    pub best_streak: u32,
    pub last_activity: u64,
    pub member_since: u64,
    pub telo_rating: u32,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct TournamentBasicInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub tournament_id: u64,
    pub game_id: u64,
    pub status: u32,
    pub participants: ManagedVec<Api, ManagedAddress<Api>>,
    pub creator: ManagedAddress<Api>,
    pub max_players: u32,
    pub min_players: u32,
    pub entry_fee: BigUint<Api>,
    pub name: ManagedBuffer<Api>,
    pub created_at: u64,
}

#[type_abi]
#[derive(TopEncode, TopDecode, ManagedVecItem, NestedEncode, NestedDecode, Clone, Debug, PartialEq)]
pub struct UserStatsInfo<Api>
where
    Api: ManagedTypeApi,
{
    pub address: ManagedAddress<Api>,
    pub stats: UserStats<Api>,
}
