// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           37
// Async Callback (empty):               1
// Total number of exported functions:  40

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tournament_hub
    (
        init => init
        upgrade => upgrade
        registerGame => register_game
        setHouseFeePercentage => set_house_fee_percentage
        submitResults => submit_results
        placeSpectatorBet => place_spectator_bet
        claimSpectatorWinnings => claim_spectator_winnings
        createTournament => create_tournament
        joinTournament => join_tournament
        startGame => start_game
        setTournamentFee => set_tournament_fee
        getPrizePool => get_prize_pool
        clearAllTournaments => clear_all_tournaments
        getGameConfig => get_game_config
        getTournament => get_tournament
        getNumberOfTournaments => get_number_of_tournaments
        getNumberOfGames => get_number_of_games
        getActiveTournamentIds => get_active_tournament_ids
        getTournamentBasicInfo => get_tournament_basic_info
        getUserTournaments => get_user_tournaments
        getSpectatorBets => get_spectator_bets
        getSpectatorPoolTotal => get_spectator_pool_total
        getAccumulatedHouseFees => get_accumulated_house_fees
        getTournamentFee => get_tournament_fee
        getHouseFeePercentage => get_house_fee_percentage
        getUserStats => get_user_stats
        getUserTournamentsCreated => get_user_tournaments_created
        getUserTournamentsJoined => get_user_tournaments_joined
        getUserTournamentsWon => get_user_tournaments_won
        getTotalTournamentsCreated => get_total_tournaments_created
        getTotalTournamentsCompleted => get_total_tournaments_completed
        getTournamentStats => get_tournament_stats
        getMaxPrizeWon => get_max_prize_won
        getTotalPrizeDistributed => get_total_prize_distributed
        getPrizeStats => get_prize_stats
        getAllActiveTournamentsBasicInfo => get_all_active_tournaments_basic_info
        getTournamentStatusSingle => get_tournament_status_single
        getTournamentBasicInfoSingle => get_tournament_basic_info_single
        getUserStatsSingle => get_user_stats_single
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
