// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                           11
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    tournament_hub
    (
        init => init
        upgrade => upgrade
        registerGame => register_game
        submitResults => submit_results
        placeSpectatorBet => place_spectator_bet
        claimSpectatorWinnings => claim_spectator_winnings
        createTournament => create_tournament
        joinTournament => join_tournament
        startTournament => start_tournament
        getGameConfig => get_game_config
        getTournament => get_tournament
        getSpectatorBets => get_spectator_bets
        getSpectatorPoolTotal => get_spectator_pool_total
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
