// Code generated by the multiversx-sc proxy generator. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

#![allow(dead_code)]
#![allow(clippy::all)]

use multiversx_sc::proxy_imports::*;

pub struct TournamentHubProxy;

impl<Env, From, To, Gas> TxProxyTrait<Env, From, To, Gas> for TournamentHubProxy
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    type TxProxyMethods = TournamentHubProxyMethods<Env, From, To, Gas>;

    fn proxy_methods(self, tx: Tx<Env, From, To, (), Gas, (), ()>) -> Self::TxProxyMethods {
        TournamentHubProxyMethods { wrapped_tx: tx }
    }
}

pub struct TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    wrapped_tx: Tx<Env, From, To, (), Gas, (), ()>,
}

#[rustfmt::skip]
impl<Env, From, Gas> TournamentHubProxyMethods<Env, From, (), Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    Gas: TxGas<Env>,
{
    pub fn init(
        self,
    ) -> TxTypedDeploy<Env, From, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_deploy()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn upgrade(
        self,
    ) -> TxTypedUpgrade<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_upgrade()
            .original_result()
    }
}

#[rustfmt::skip]
impl<Env, From, To, Gas> TournamentHubProxyMethods<Env, From, To, Gas>
where
    Env: TxEnv,
    Env::Api: VMApi,
    From: TxFrom<Env>,
    To: TxTo<Env>,
    Gas: TxGas<Env>,
{
    pub fn register_game<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
        Arg2: ProxyArg<u32>,
        Arg3: ProxyArg<ManagedVec<Env::Api, u32>>,
        Arg4: ProxyArg<u32>,
        Arg5: ProxyArg<bool>,
    >(
        self,
        game_id: Arg0,
        signing_server_address: Arg1,
        podium_size: Arg2,
        prize_distribution_percentages: Arg3,
        house_fee_percentage: Arg4,
        allow_late_join: Arg5,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("registerGame")
            .argument(&game_id)
            .argument(&signing_server_address)
            .argument(&podium_size)
            .argument(&prize_distribution_percentages)
            .argument(&house_fee_percentage)
            .argument(&allow_late_join)
            .original_result()
    }

    pub fn submit_results<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedVec<Env::Api, ManagedAddress<Env::Api>>>,
        Arg2: ProxyArg<ManagedBuffer<Env::Api>>,
    >(
        self,
        tournament_id: Arg0,
        winner_podium: Arg1,
        signed_result: Arg2,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("submitResults")
            .argument(&tournament_id)
            .argument(&winner_podium)
            .argument(&signed_result)
            .original_result()
    }

    pub fn place_spectator_bet<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<ManagedAddress<Env::Api>>,
    >(
        self,
        tournament_id: Arg0,
        betting_on_player: Arg1,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("placeSpectatorBet")
            .argument(&tournament_id)
            .argument(&betting_on_player)
            .original_result()
    }

    pub fn claim_spectator_winnings<
        Arg0: ProxyArg<u64>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("claimSpectatorWinnings")
            .argument(&tournament_id)
            .original_result()
    }

    pub fn create_tournament<
        Arg0: ProxyArg<u64>,
        Arg1: ProxyArg<u64>,
        Arg2: ProxyArg<BigUint<Env::Api>>,
        Arg3: ProxyArg<u64>,
        Arg4: ProxyArg<u64>,
    >(
        self,
        tournament_id: Arg0,
        game_id: Arg1,
        entry_fee: Arg2,
        join_deadline: Arg3,
        play_deadline: Arg4,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("createTournament")
            .argument(&tournament_id)
            .argument(&game_id)
            .argument(&entry_fee)
            .argument(&join_deadline)
            .argument(&play_deadline)
            .original_result()
    }

    pub fn join_tournament<
        Arg0: ProxyArg<u64>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, (), Gas, ()> {
        self.wrapped_tx
            .raw_call("joinTournament")
            .argument(&tournament_id)
            .original_result()
    }

    pub fn start_tournament<
        Arg0: ProxyArg<u64>,
    >(
        self,
        tournament_id: Arg0,
    ) -> TxTypedCall<Env, From, To, NotPayable, Gas, ()> {
        self.wrapped_tx
            .payment(NotPayable)
            .raw_call("startTournament")
            .argument(&tournament_id)
            .original_result()
    }
}
